server:
  port: 8080
  servlet:
    context-path: /inspect

##mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/erpsdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

#mybatis
mybatis:
  type-aliases-package: com.fortis.inspection.entity
  mapper-locations: classpath:mappers/*.xml



