server:
  port: 8081
  servlet:
    context-path: /ins-manage

##mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.11.33:3306/ceprsdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: ceprs
    password: z55Pv#Vh

#mybatis
mybatis:
  type-aliases-package: com.fortis.inspection.entity
  mapper-locations: classpath:mappers/*.xml



