server:
  port: 8080
  servlet:
    context-path: /inspect

spring:
  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.11.33:3306/eprdsdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    username: eprds-web
    password: Jq7.0$z4dOs

  #redis配置
  redis:
    host: 172.20.1.39
    port: 6379
    database: 8
    password: 123456
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: 60000

#mybatis
mybatis:
  type-aliases-package: com.fortis.inspection.entity,com.fortis.inspection.model
  mapper-locations: classpath:mappers/*.xml



